# Generated by Django 5.1.5 on 2025-01-27 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RailwayCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('railway_name', models.CharField(max_length=255)),
                ('railway_description', models.TextField()),
                ('refund_policy', models.TextField()),
                ('railway_logo', models.ImageField(blank=True, null=True, upload_to='railway_company_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=255)),
                ('station_city', models.CharField(max_length=255)),
                ('station_province', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TrainHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_name', models.CharField(max_length=255)),
                ('hall_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=50, unique=True)),
                ('departure_datetime', models.DateTimeField()),
                ('arrival_datetime', models.DateTimeField()),
                ('train_type', models.CharField(choices=[('4_coupe', 'Coupe 4-seater'), ('bus', 'Bus-style'), ('6_coupe', 'Coupe 6-seater')], max_length=20)),
                ('capacity', models.IntegerField()),
                ('stars', models.IntegerField(default=3)),
                ('base_price', models.BigIntegerField()),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('arrival_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='Train.station')),
                ('departure_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='Train.station')),
                ('railway_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Train.railwaycompany')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Train.trainhall')),
            ],
        ),
    ]
