# Generated by Django 5.1.5 on 2025-01-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Train', '0002_train_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='final_price',
            field=models.BigIntegerField(),
        ),
    ]
