# Generated by Django 5.1.5 on 2025-02-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Train', '0003_alter_train_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='train_type',
            field=models.CharField(choices=[('COUPE_4_SEATER', 'Coupe 4-seater'), ('BUS_STYLE', 'Bus-style'), ('COUPE_6_SEATER', 'Coupe 6-seater')], max_length=20),
        ),
    ]
